DROP TABLE DEPARTAMENTOS CASCADE CONSTRAINTS;
DROP TABLE EMPLEADOS CASCADE CONSTRAINTS;
DROP TABLE EMPLEADOS_DEPARTAMENTOS CASCADE CONSTRAINTS;
DROP TABLE EMPLEADOS_ESTUDIOS CASCADE CONSTRAINTS;
DROP TABLE ESTUDIOS_EMPLEADOS CASCADE CONSTRAINTS;

CREATE TABLE DEPARTAMENTOS (
    CODIGO NUMBER(2) NOT NULL,
    NOMBRE VARCHAR2(25) NOT NULL CHECK(NOMBRE IN ('CONTABILIDAD','ADMINISTRACION','VENTAS','RECURSOS_HUMANOS')),
    DPTO_PADRE NUMBER(2),
    PRESUPUESTO NUMBER,
    CONSTRAINT DEP_PK PRIMARY KEY (CODIGO),
    CONSTRAINT DEP_FK FOREIGN KEY (DPTO_PADRE) REFERENCES DEPARTAMENTOS(CODIGO)
    );
CREATE TABLE EMPLEADOS (
    DNI VARCHAR2(9) NOT NULL,
    NOMBRE VARCHAR2(50) NOT NULL,
    DIRECCION VARCHAR2(50) NOT NULL,
    PROVINCIA VARCHAR2(25) NOT NULL CHECK(PROVINCIA =UPPER(PROVINCIA)),
    COD_POSTAL NUMBER(5) NOT NULL,
    FECHA_NACIMIENTO DATE,
    CONSTRAINT EMP_PK3 PRIMARY KEY (DNI)
    );
CREATE TABLE EMPLEADOS_DEPARTAMENTOS (
    EMPLEADO VARCHAR(9) NOT NULL,
    DEPARTAMENTO NUMBER(2) NOT NULL,
    F_INICIO DATE,
    F_FIN DATE,
    SALARIO NUMBER(6,2) CHECK (SALARIO BETWEEN 1500 AND 6000),
    CONSTRAINT EMP_DEP_PK PRIMARY KEY (EMPLEADO, DEPARTAMENTO),
    CONSTRAINT EMP_DEP_FK FOREIGN KEY (DEPARTAMENTO) REFERENCES DEPARTAMENTOS(CODIGO),
    CONSTRAINT EMP_DEP_FK2 FOREIGN KEY (EMPLEADO) REFERENCES EMPLEADOS(DNI)
    );
CREATE TABLE EMPLEADOS_ESTUDIOS (
    DNI VARCHAR2(9) NOT NULL,
    UNIVERSIDAD NUMBER(5) NOT NULL,
    AÑO NUMBER(4) NOT NULL,
    TITULO VARCHAR2(30) NOT NULL,
    CONSTRAINT EMP_EST_PK2 PRIMARY KEY (DNI),
    CONSTRAINT EMP_EST_FK FOREIGN KEY (DNI) REFERENCES EMPLEADOS(DNI)
    );
    
    
ALTER TABLE EMPLEADOS_DEPARTAMENTOS RENAME COLUMN EMPLEADO TO NIF
;
ALTER TABLE DEPARTAMENTOS ADD ( 
RESPONSABLE VARCHAR2(9),
CONSTRAINT RES_FK FOREIGN KEY (RESPONSABLE) REFERENCES EMPLEADOS(DNI)
);
RENAME EMPLEADOS_ESTUDIOS TO ESTUDIOS_EMPLEADOS
;

