--1.El nombre del producto más caro.
    SELECT NOMBRE, PRECIOVENTA FROM PRODUCTOS
    WHERE PRECIOVENTA=
    (SELECT MAX(PRECIOVENTA) FROM PRODUCTOS);
--2.El nombre del producto del que más unidades se hayan vendido en un mismo pedido.
    SELECT NOMBRE FROM PRODUCTOS
    WHERE CODIGOPRODUCTO=
    (SELECT CODIGOPRODUCTO FROM DETALLEPEDIDOS
    WHERE CANTIDAD=
    (SELECT MAX(CANTIDAD) FROM DETALLEPEDIDOS));
--3.Los clientes cuya línea de crédito sea mayor que los pagos que hayan realizado.
    SELECT CODIGOCLIENTE, NOMBRECLIENTE
    FROM CLIENTES
    WHERE LIMITECREDITO >
    (SELECT SUM(CANTIDAD)
    FROM PAGOS
    WHERE CLIENTES.CODIGOCLIENTE=PAGOS.CODIGOCLIENTE
    GROUP BY CODIGOCLIENTE);
--4.El producto que más unidades tiene en stock y el que menos unidades tiene.
    SELECT NOMBRE, CANTIDADENSTOCK FROM PRODUCTOS
    WHERE CANTIDADENSTOCK=
    (SELECT MAX(CANTIDADENSTOCK) FROM PRODUCTOS)
    OR CANTIDADENSTOCK=
    (SELECT MIN(CANTIDADENSTOCK) FROM PRODUCTOS);
